[package]
name = "cuttle"
version = "0.1.0"
edition = "2021"

[features]
default = ["builtins"]
builtins = []

[dependencies.bevy]
version = "0.15"
default-features = false
features = [
    "bevy_asset",
    "bevy_render",
    "bevy_core_pipeline",
    "bevy_ui",
    "x11",
    "bevy_gizmos",
    "png",
    "bevy_window"
]

[dependencies]
bytemuck = "1"
convert_case = "0.6"
serde = "1"
derive_more = "1"

[dev-dependencies]
rand = "0.8"