[package]
name = "bevy_comdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.bevy]
version = "0.15.0-rc.1"
# git = "https://github.com/bevyengine/bevy"
# branch = "main"
default-features = false
features = ["bevy_asset", "bevy_render", "bevy_core_pipeline", "bevy_ui", "x11"]

[dependencies]
bytemuck = "1"
itertools = "0.13"
convert_case = "0.6"

[dev-dependencies]
rand = "0.8"
# bevy_editor_pls = "0"
