[package]
name = "cuttle"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = ["crates/cuttle_core", "crates/cuttle_macros", "crates/cuttle_sdf"]

[features]
default = ["sdf"]
sdf = ["cuttle_sdf"]

[dependencies]
cuttle_core = { path = "crates/cuttle_core" }
cuttle_macros = { path = "crates/cuttle_macros" }
cuttle_sdf = { path = "crates/cuttle_sdf", optional = true }

bevy_app = "0.15"

[dev-dependencies]
bevy = "0.15"
rand = "0.9.0"
bevy-inspector-egui = "0.29.1"